version: '3'

services:
  web_server:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: andrew123456
    volumes:
        - ./db_data:/docker-entrypoint-initdb.d
        - db_volume:/var/lib/mysql
    restart: always

volumes:
  db_volume: